name: vrouter
description: A navigation package that makes navigation and routing easy on every platform. Built on top of Navigator 2.
version: 1.2.1
homepage: https://vrouter.dev
repository: https://github.com/lulupointu/vrouter
publish_to: 'none'
environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_strategy: ^0.2.0
  url_launcher: ^6.3.0
  move_to_background:
    git:
      url: https://github.com/incrediblezayed/move_to_background
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  coverage:
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true